name: Publish to GitHub Packages

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish-github:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@mattraus'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Run linting
        run: npm run lint

      - name: Check formatting
        run: npm run format:check

      - name: Build project
        run: npm run build

      - name: Update package name for GitHub Packages
        run: npm pkg set name="@mattraus/odesli.js"

      - name: Debug authentication
        run: |
          echo "Testing GitHub Packages authentication..."
          npm whoami --registry=https://npm.pkg.github.com || echo "Authentication failed"
          echo "Current package name:"
          npm pkg get name
          echo "Setting package name to @mattraus/odesli.js"
          npm pkg set name="@mattraus/odesli.js"
          echo "Updated package name:"
          npm pkg get name

      - name: Publish to GitHub Packages
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
